version: "3.3"
services:
    back:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: study-backend
        environment:
            - isDocker=true
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./backend:/study-back
            - /study-back/node_modules/
        depends_on:
            - db
        command: bash -c 'yarn install && yarn start:dev'
    front:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - back
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/study-front
            - /study-front/node_modules
        command: bash -c 'yarn install && yarn start'
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "labs"
        volumes:
            - ./dbdata/pgdata:/var/lib/postgresql/data
            - ./dbdata/backups:/var/lib/postgresql
        ports:
            - "5433:5432"
