version: "3.3"
services:
    back:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        container_name: study-backend
        security_opt:
            - apparmor:unconfined
        environment:
            - isDocker=true
            - NODE_ENV=production
        restart: always
        ports:
            - "3002:3001"
        command: yarn start:prod
    front:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        container_name: study-frontend
        security_opt:
            - apparmor:unconfined
        environment:
            - NODE_ENV=production
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - back
        command: serve -s build -p 3000
