version: "3.3"
services:
    back:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        container_name: study-backend
        security_opt:
            - apparmor:unconfined
        environment:
            - isDocker=true
            - NODE_ENV=production
        restart: always
        ports:
            - "3002:3001"
        command: bash -c "yarn build && yarn start:prod"
    front:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        container_name: study-frontend
        security_opt:
            - apparmor:unconfined
        restart: always
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - back
        command: bash -c "yarn build && serve -s build -p 3000"
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "labs"
        volumes:
            - ./dbdata/pgdata:/var/lib/postgresql/data
            - ./dbdata/backups:/var/lib/postgresql
        ports:
            - "5433:5432"
