name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    first:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: ssh connection and Deployment
              uses: appleboy/ssh-action@master
              with:
                  host: 194.61.2.188
                  username: root
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd labs
                      git pull origin master
                      docker-compose -f docker-compose.prod.yml up --build -d
